<a href="https://colab.research.google.com/github/krishnasaicareer/Sample/blob/main/U1W2_05_Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
### Not For Grading

### Learning Objective



At the end of this experiment, you will be able to :

* Use Pandas Library

### Dataset

#### Description

The dataset choosen for this exercise is an employee dataset. The dataset contains the following information regarding a particular employee:

* Emp ID
* Name Prefix
* First Name
* Middle Initial
* Last Name
* Gender
* E Mail
* Father's Name
* Mother's Name
* Mother's Maiden Name
* Date of Birth
* Time of Birth
* Age in Yrs
*  Weight in Kgs
* Date of Joining
* Quarter of Joining
* Half of Joining
* Year of Joining
* Month of Joining
* Month Name of Joining
* Short Month
* Day of Joining
* DOW of Joining
* Short DOW
* Age in Company (Years)
* Salary
* Last % Hike
* SSN
* Phone No
* Place Name
* CountyCity,
* State
* Zip
* Region
* User Name
* Password

## Setup Steps

In [1]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2501978" #@param {type:"string"}

In [2]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "9745866112" #@param {type:"string"}

In [3]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "U1W2_05_Introduction_to_Pandas" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.talentsprint.com/aiml/Experiment_related_data/Employee.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/submissions/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword(), "batch" : ""}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook, "batch" : ""}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")

Setup completed successfully

## 1. Load the dataset with index as 'Emp Id'

In [4]:
import pandas as pd

In [12]:
dataset = pd.read_csv("Employee.csv")
print(dataset.head())
ds = dataset.set_index("Emp ID")
print(ds.head())
# YOUR CODE HERE

   Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
0  677509        Drs.       Lois              H    Walker      F
1  940761         Ms.     Brenda              S  Robinson      F
2  428945         Dr.        Joe              W  Robinson      M
3  408351        Drs.      Diane              I     Evans      F
4  193819         Mr.   Benjamin              R   Russell      M

                         E Mail     Father's Name       Mother's Name  \
0       lois.walker@hotmail.com     Donald Walker        Helen Walker
1     brenda.robinson@gmail.com  Raymond Robinson       Judy Robinson
2        joe.robinson@gmail.com    Scott Robinson  Stephanie Robinson
3         diane.evans@yahoo.com       Jason Evans      Michelle Evans
4  benjamin.russell@charter.net   Gregory Russell   Elizabeth Russell

  Mother's Maiden Name  ...          SSN    Phone No.     Place Name  \
0                Lewis  ...  467-99-4677  303-572-8492        Denver
1                Perry  ...  537-71-4566  225-945-4954     Stonewall
2               Taylor  ...  025-92-3584  219-904-2161  Michigantown
3                Allen  ...  314-35-9851  215-793-6791      Hydetown
4               Nelson  ...  121-98-7248  262-404-2252       Fremont

     County          City State    Zip     Region   User Name        Password
0    Denver        Denver    CO  80224       West    lhwalker   DCa}.T}X:v?NP
1   De Soto     Stonewall    LA  71078      South  bsrobinson   TCo\j#Zg;SQ~o
2   Clinton  Michigantown    IN  46057    Midwest  jwrobinson    GO4$J8MiEh[A
3  Crawford      Hydetown    PA  16328  Northeast     dievans   0gGRtp1HfL<r5
4   Waupaca       Fremont    WI  54940    Midwest   brrussell  Rd<Y8cp!@R;*%F

[5 rows x 37 columns]
       Name Prefix First Name Middle Initial Last Name Gender  \
Emp ID
677509        Drs.       Lois              H    Walker      F
940761         Ms.     Brenda              S  Robinson      F
428945         Dr.        Joe              W  Robinson      M
408351        Drs.      Diane              I     Evans      F
193819         Mr.   Benjamin              R   Russell      M

                              E Mail     Father's Name       Mother's Name  \
Emp ID
677509       lois.walker@hotmail.com     Donald Walker        Helen Walker
940761     brenda.robinson@gmail.com  Raymond Robinson       Judy Robinson
428945        joe.robinson@gmail.com    Scott Robinson  Stephanie Robinson
408351         diane.evans@yahoo.com       Jason Evans      Michelle Evans
193819  benjamin.russell@charter.net   Gregory Russell   Elizabeth Russell

       Mother's Maiden Name Date of Birth  ...          SSN    Phone No.   \
Emp ID                                     ...
677509                Lewis     3/29/1981  ...  467-99-4677  303-572-8492
940761                Perry     7/31/1970  ...  537-71-4566  225-945-4954
428945               Taylor     6/16/1963  ...  025-92-3584  219-904-2161
408351                Allen     12/4/1977  ...  314-35-9851  215-793-6791
193819               Nelson     4/17/1977  ...  121-98-7248  262-404-2252

          Place Name    County          City State    Zip     Region  \
Emp ID
677509        Denver    Denver        Denver    CO  80224       West
940761     Stonewall   De Soto     Stonewall    LA  71078      South
428945  Michigantown   Clinton  Michigantown    IN  46057    Midwest
408351      Hydetown  Crawford      Hydetown    PA  16328  Northeast
193819       Fremont   Waupaca       Fremont    WI  54940    Midwest

         User Name        Password
Emp ID
677509    lhwalker   DCa}.T}X:v?NP
940761  bsrobinson   TCo\j#Zg;SQ~o
428945  jwrobinson    GO4$J8MiEh[A
408351     dievans   0gGRtp1HfL<r5
193819   brrussell  Rd<Y8cp!@R;*%F

[5 rows x 36 columns]

### 2. Display the first 5 entries of the dataset

In [13]:
# YOUR CODE HERE
dataset.head()

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,...,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,...,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F

### 3. How many  records are there in the dataset?

In [14]:
# YOUR CODE HERE
dataset.shape[0]

100

### 4. How many columns are there in the dataset?

In [15]:
# YOUR CODE HERE
dataset.shape[1]

37

### 5. Print the name of all the columns in the dataset

In [16]:
# YOUR CODE HERE
dataset.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

### 6. What is  the name of the 20th column ?

In [18]:
# YOUR CODE HERE
dataset.axes[1][19]

'Month Name of Joining'

### 7. What is  the datatype of each column in the dataset?

In [19]:
# YOUR CODE HERE
dataset.dtypes

Emp ID                      int64
Name Prefix                object
First Name                 object
Middle Initial             object
Last Name                  object
Gender                     object
E Mail                     object
Father's Name              object
Mother's Name              object
Mother's Maiden Name       object
Date of Birth              object
Time of Birth              object
Age in Yrs.               float64
Weight in Kgs.              int64
Date of Joining            object
Quarter of Joining         object
Half of Joining            object
Year of Joining             int64
Month of Joining            int64
Month Name of Joining      object
Short Month                object
Day of Joining              int64
DOW of Joining             object
Short DOW                  object
Age in Company (Years)    float64
Salary                      int64
Last % Hike                object
SSN                        object
Phone No.                  object
Place Name                 object
County                     object
City                       object
State                      object
Zip                         int64
Region                     object
User Name                  object
Password                   object
dtype: object

### 8. Display the columns from 5 to 9 and rows 1 to 3 of the dataset

In [21]:
# YOUR CODE HERE
dataset.iloc[0:3, 5:10]

,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name
0,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis
1,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry
2,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor

### 9. Display all the rows after 50th row of the dataset

In [24]:
# YOUR CODE HERE
dataset.iloc[50:]

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
50,958326,Mr.,Larry,T,Miller,M,larry.miller@shell.com,Russell Miller,Mildred Miller,Ward,...,207-84-9482,217-574-9283,East Saint Louis,St. Clair,East Saint Louis,IL,62201,Midwest,ltmiller,2WgF#:ew**x#
51,447813,Mrs.,Ann,Q,Coleman,F,ann.coleman@ibm.com,Harold Coleman,Tina Coleman,Walker,...,027-92-0557,319-994-4179,Hancock,Pottawattamie,Hancock,IA,51536,Midwest,aqcoleman,g2]GlvlL5
52,525955,Drs.,Judy,C,Gonzales,F,judy.gonzales@gmail.com,Kevin Gonzales,Sharon Gonzales,Perez,...,029-92-2155,201-640-8645,Eatontown,Monmouth,Eatontown,NJ,7724,Northeast,jcgonzales,yDl}pfaWs{Hro6
53,818384,Mr.,Peter,X,Washington,M,peter.washington@bp.com,Douglas Washington,Jean Washington,Henderson,...,039-74-8867,231-322-0316,Portage,Kalamazoo,Portage,MI,49024,Midwest,pxwashington,97%d^2rk41!E>*Q
54,971640,Prof.,Clarence,A,Ross,M,clarence.ross@apple.com,Arthur Ross,Louise Ross,Washington,...,372-37-5315,423-772-0118,Oneida,Scott,Oneida,TN,37841,South,caross,h&jmac@+QD?B
55,253573,Ms.,Sharon,E,Lopez,F,sharon.lopez@gmail.com,Daniel Lopez,Susan Lopez,Hayes,...,064-02-2589,304-934-5548,Bartley,McDowell,Bartley,WV,24813,South,selopez,GsP~S?FYY
56,904898,Drs.,Ann,Q,Cooper,F,ann.cooper@exxonmobil.com,Harold Cooper,Mildred Cooper,Williams,...,219-89-6310,406-278-6460,Arlee,Lake,Arlee,MT,59821,West,aqcooper,i_^#>]tFpt
57,515103,Ms.,Anne,A,Perez,F,anne.perez@sbcglobal.net,Douglas Perez,Doris Perez,Bailey,...,594-99-9091,423-837-3338,Cookeville,Putnam,Cookeville,TN,38505,South,aaperez,y;n9A#}b
58,491943,Mrs.,Nancy,P,Howard,F,nancy.howard@gmail.com,Gregory Howard,Mildred Howard,Flores,...,035-74-2732,236-973-8086,Saxe,Charlotte,Saxe,VA,23967,South,nphoward,OC\&tG&?c
59,750173,Mr.,Antonio,R,Roberts,M,antonio.roberts@hotmail.com,Timothy Roberts,Diana Roberts,Rodriguez,...,281-15-7944,205-267-7304,Mc Calla,Jefferson,Mc Calla,AL,35111,South,arroberts,h>.g!B:VcNN
60,687017,Ms.,Frances,P,Watson,F,frances.watson@outlook.com,Adam Watson,Diana Watson,Jones,...,305-37-1946,406-530-8069,Trego,Lincoln,Trego,MT,59934,West,fpwatson,rjV1$at!wq53a$
61,241882,Ms.,Debra,G,Wood,F,debra.wood@hotmail.com,Martin Wood,Theresa Wood,Perry,...,342-11-6695,308-646-6219,Blair,Washington,Blair,NE,68009,Midwest,dgwood,iO8B@*yA*mG6b9o
62,758872,Mr.,Henry,Y,Jenkins,M,henry.jenkins@hotmail.com,Albert Jenkins,Beverly Jenkins,Murphy,...,499-29-3125,314-731-7135,Riverside,Platte,Riverside,MO,64150,Midwest,hyjenkins,zPnRU5Bo
63,940922,Hon.,Melissa,X,Butler,F,melissa.butler@hotmail.com,Robert Butler,Anne Butler,Jackson,...,301-15-9149,308-827-9016,Maxwell,Lincoln,Maxwell,NE,69151,Midwest,mxbutler,hY3BqUR>6F
64,917937,Mr.,Todd,H,Hall,M,todd.hall@yahoo.com,Thomas Hall,Kathleen Hall,Morgan,...,633-31-1781,240-513-8668,Randallstown,Baltimore,Randallstown,MD,21133,South,thhall,Lgdb8q<0L@-/
65,917395,Hon.,Christopher,D,Nelson,M,christopher.nelson@aol.com,Jeffrey Nelson,Cynthia Nelson,Sanders,...,120-98-6155,480-946-9780,Willow Beach,Mohave,Willow Beach,AZ,86445,West,cdnelson,QKae{1EP1A[SeX
66,183071,Drs.,Andrea,P,Garcia,F,andrea.garcia@aol.com,Mark Garcia,Nicole Garcia,Howard,...,213-91-6792,219-624-3708,Granger,St. Joseph,Granger,IN,46530,Midwest,apgarcia,eI!^kXR]Q^V+
67,316110,Mr.,Jeremy,I,Sanchez,M,jeremy.sanchez@hotmail.com,Albert Sanchez,Patricia Sanchez,Ross,...,474-55-8883,423-974-2755,Alcoa,Blount,Alcoa,TN,37701,South,jisanchez,Yg#Z+:CDwDV<*xZ
68,293459,Mr.,Steven,J,Phillips,M,steven.phillips@hotmail.com,Jason Phillips,Gloria Phillips,Lewis,...,578-53-9940,225-968-5952,Baton Rouge,East Baton Rouge,Baton Rouge,LA,70833,South,sjphillips,ht}X55$P&g1
69,732017,Ms.,Cynthia,J,Ramirez,F,cynthia.ramirez@btinternet.com,Walter Ramirez,Evelyn Ramirez,Smith,...,355-08-4606,406-961-7340,Browning,Glacier,Browning,MT,59417,West,cjramirez,qP-#AhuNuz*Wb]
70,915638,Dr.,Jason,W,Anderson,M,jason.anderson@gmail.com,Brandon Anderson,Julia Anderson,Baker,...,048-15-7937,217-856-6752,Hudson,McLean,Hudson,IL,61748,Midwest,jwanderson,a3Hlk+.V/TjD
71,478003,Hon.,Cynthia,X,White,F,cynthia.white@gmail.com,Nicholas White,Katherine White,Turner,...,364-39-4983,314-593-3092,Kansas City,Jackson,Kansas City,MO,64133,Midwest,cxwhite,mofyGR>.?Dwb4!
72,951225,Ms.,Margaret,N,Brooks,F,margaret.brooks@gmail.com,Johnny Brooks,Debra Brooks,Robinson,...,057-02-6958,303-960-0117,Haswell,Kiowa,Haswell,CO,81045,West,mnbrooks,0*2k8uW&:{i{
73,883936,Mr.,Douglas,I,Flores,M,douglas.flores@gmail.com,Justin Flores,Kathy Flores,Ramirez,...,324-11-6837,303-836-4721,Eckert,Delta,Eckert,CO,81418,West,diflores,9||FLq|0tU|9>v
74,528673,Hon.,Paul,V,Watson,M,paul.watson@hotmail.com,Carl Watson,Anna Watson,Bennett,...,286-15-9671,270-556-7711,Blue River,Floyd,Blue River,KY,41607,South,pvwatson,7q{iHhbgWZ7%
75,765850,Mrs.,Linda,R,Moore,F,linda.moore@gmail.com,Howard Moore,Diana Moore,Smith,...,286-15-5442,215-793-7095,Albion,Erie,Albion,PA,16401,Northeast,lrmoore,0jj}jl_r/VmJ;
76,262382,Ms.,Cheryl,O,Miller,F,cheryl.miller@ntlworld.com,Gerald Miller,Christine Miller,Mitchell,...,287-15-4772,270-880-3858,Bays,Breathitt,Bays,KY,41310,South,comiller,Nr-t/.^cWBO
77,870820,Ms.,Martha,G,Washington,F,martha.washington@aol.com,Todd Washington,Carolyn Washington,Reed,...,416-67-0297,405-945-0242,Nardin,Kay,Nardin,OK,74646,South,mgwashington,ju$7I]eH8{-
78,806955,Mr.,William,G,Hernandez,M,william.hernandez@rediffmail.com,Peter Hernandez,Deborah Hernandez,Jones,...,629-31-9010,239-276-0532,Mary Esther,Okaloosa,Mary Esther,FL,32569,South,wghernandez,BRB3DFywgZZ4
79,325319,Hon.,Carolyn,F,Price,F,carolyn.price@yahoo.com,Kevin Price,Patricia Price,Williams,...,512-33-3410,217-409-4338,Wheaton,DuPage,Wheaton,IL,60189,Midwest,cfprice,K*$u@MAoH
80,623253,Mrs.,Ruby,Q,Stewart,F,ruby.stewart@gmail.com,Paul Stewart,Paula Stewart,Jackson,...,007-11-1727,218-445-2369,Margie,Koochiching,Margie,MN,56658,Midwest,rqstewart,C\RjCUPJd[Ld]
81,225925,Mr.,Paul,D,Cooper,M,paul.cooper@gmail.com,Nicholas Cooper,Helen Cooper,Hill,...,613-87-0084,210-984-4722,Glidden,Colorado,Glidden,TX,78943,South,pdcooper,hW%ZbJ\fZ-
82,761821,Mr.,Ernest,G,Washington,M,ernest.washington@msn.com,Johnny Washington,Shirley Washington,Harris,...,178-86-1878,212-596-1659,Saranac Lake,Franklin,Saranac Lake,NY,12983,Northeast,egwashington,B\Wb^6W-
83,400173,Ms.,Dorothy,K,Edwards,F,dorothy.edwards@hotmail.co.uk,Dennis Edwards,Betty Edwards,Howard,...,543-81-2192,215-902-6888,Philadelphia,Philadelphia,Philadelphia,PA,19132,Northeast,dkedwards,VWEIm3YKm65|D
84,802554,Mr.,Ryan,V,Alexander,M,ryan.alexander@shell.com,William Alexander,Elizabeth Alexander,Gray,...,017-94-7572,225-395-3347,Jarreau,Pointe Coupee,Jarreau,LA,70749,South,rvalexander,3N3]VFZx?MaC{
85,476433,Ms.,Lillian,N,Mitchell,F,lillian.mitchell@shaw.ca,Harry Mitchell,Marie Mitchell,Murphy,...,505-59-3960,316-876-1484,Wichita,Sedgwick,Wichita,KS,67214,Midwest,lnmitchell,Ty/b@+;f
86,533952,Ms.,Kelly,R,Adams,F,kelly.adams@bp.com,Eric Adams,Janice Adams,Brooks,...,474-55-8101,405-418-0037,Meno,Major,Meno,OK,73760,South,kradams,OfK?#J|7&W\1T
87,623929,Prof.,Jimmy,R,Howard,M,jimmy.howard@yahoo.com,Nicholas Howard,Patricia Howard,Hayes,...,610-87-0251,212-855-9316,Oriskany,Oneida,Oriskany,NY,13424,Northeast,jrhoward,0v+|SfA0Xv+Pf%
88,844177,Ms.,Margaret,T,Allen,F,margaret.allen@gmail.com,Michael Allen,Karen Allen,Morris,...,137-25-8468,216-697-6987,Richmond Dale,Ross,Richmond Dale,OH,45673,Midwest,mtallen,oC1OHlW%Sk@%6
89,212893,Ms.,Janet,Y,Henderson,F,janet.henderson@ntlworld.com,Jerry Henderson,Julie Henderson,Cooper,...,018-94-7340,239-769-6347,Miami,Miami-Dade,Miami,FL,33166,South,jyhenderson,g-oCs-L/za
90,185032,Mr.,Eugene,D,Perez,M,eugene.perez@exxonmobil.com,Jimmy Perez,Lois Perez,Hall,...,192-86-6418,262-472-7112,Racine,Racine,Racine,WI,53490,Midwest,edperez,g]SJn<W_/#
91,867084,Ms.,Deborah,E,Smith,F,deborah.smith@yahoo.com,Richard Smith,Diana Smith,Bennett,...,173-86-6203,907-279-8694,Atqasuk,North Slope,Atqasuk,AK,99791,West,desmith,C[WxHsB9
92,969964,Hon.,Janice,S,Parker,F,janice.parker@yahoo.com,Paul Parker,Alice Parker,Perez,...,733-26-1976,314-842-5984,Whiteman Air Force Base,Johnson,Whiteman Air Force Base,MO,65305,Midwest,jsparker,8wUbWmuib
93,158666,Ms.,Rebecca,A,Stewart,F,rebecca.stewart@gmail.com,Roger Stewart,Carol Stewart,Cox,...,202-84-8294,209-233-7631,Independence,Inyo,Independence,CA,93526,West,rastewart,7ONuh3Zi^z#32r
94,489424,Dr.,Phillip,F,White,M,phillip.white@gmail.com,Harold White,Frances White,Carter,...,447-27-9469,503-668-6592,Mapleton,Lane,Mapleton,OR,97453,West,pfwhite,8<Mc.5]eu.*C8.
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,...,171-86-3825,228-245-5000,Biloxi,Harrison,Biloxi,MS,39532,South,jkhill,a_!SKb6h3?w*Mad
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,...,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,...,249-99-8801,907-356-1555,Mc Grath,Yukon-Koyukuk (CA),Mc Grath,AK,99627,West,trmurphy,V]PGw>4h9
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,...,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

### 10. Display the columns from 10 to 12 for first 50 rows of the dataset

In [25]:
# YOUR CODE HERE
dataset.iloc[:50,10:13]

   Date of Birth Time of Birth  Age in Yrs.
0      3/29/1981   02:31:49 AM        36.36
1      7/31/1970   12:13:27 PM        47.02
2      6/16/1963   10:45:36 AM        54.15
3      12/4/1977   02:18:45 AM        39.67
4      4/17/1977   05:41:11 PM        40.31
5      9/27/1982   01:12:41 PM        34.86
6      6/13/1995   08:56:32 PM        22.14
7      6/30/1958   10:39:33 AM        59.12
8       6/9/1959   04:38:47 PM        58.18
9     11/13/1987   03:59:26 AM        29.73
10      2/5/1975   02:15:50 AM        42.50
11     5/19/1995   04:33:57 PM        22.21
12     2/24/1972   06:04:57 PM        45.45
13     6/26/1996   12:23:21 AM        21.10
14     2/23/1958   06:59:29 PM        59.47
15     8/22/1966   08:11:15 PM        50.97
16     5/18/1970   03:47:46 AM        47.23
17     12/5/1992   09:20:52 AM        24.66
18     7/15/1959   09:24:39 PM        58.08
19     10/4/1967   08:28:14 PM        49.85
20    12/14/1994   09:28:36 AM        22.64
21    10/26/1993   01:37:48 AM        23.77
22    11/20/1972   11:14:04 AM        44.72
23      5/1/1980   01:08:30 PM        37.27
24     3/10/1958   12:52:37 PM        59.42
25     7/29/1989   02:57:12 AM        28.02
26      1/1/1990   07:24:56 PM        27.59
27      7/7/1969   03:46:56 PM        48.09
28     3/19/1975   11:07:50 PM        42.39
29     12/6/1963   03:15:30 AM        53.68
30     5/12/1981   12:00:55 AM        36.24
31     6/16/1981   04:20:22 AM        36.14
32     8/31/1993   12:23:15 AM        23.92
33      5/8/1991   12:13:48 AM        26.24
34     7/28/1993   06:30:29 AM        24.02
35     12/1/1967   01:45:41 AM        49.69
36     2/10/1969   03:42:13 AM        48.49
37     9/14/1983   05:05:35 AM        33.89
38    12/22/1973   02:18:24 PM        43.63
39     8/22/1961   02:54:56 AM        55.97
40     6/21/1962   12:02:11 AM        55.14
41     7/29/1982   02:43:26 AM        35.02
42      1/4/1985   02:25:34 PM        32.58
43    12/11/1978   09:46:54 PM        38.65
44     8/15/1964   05:45:35 AM        52.99
45    11/14/1983   02:51:17 AM        33.73
46     11/9/1989   10:28:03 PM        27.73
47     3/25/1961   05:49:46 AM        56.38
48    11/10/1993   03:06:00 AM        23.73
49     4/14/1996   03:43:43 AM        21.30

### 11. Display the information of the employees who have  joined in Quarter 1 and 4.

In [44]:
# YOUR CODE HERE

dataset1 = pd.read_csv("Employee.csv")


subset = dataset1[dataset1['Quarter of Joining'].isin(['Q1', 'Q4'])]
empiD = subset[subset['Emp ID']=='940761'];
print("Empid is", empiD)

print(subset)

Empid is Empty DataFrame
Columns: [Emp ID, Name Prefix, First Name, Middle Initial, Last Name, Gender, E Mail, Father's Name, Mother's Name, Mother's Maiden Name, Date of Birth, Time of Birth, Age in Yrs., Weight in Kgs., Date of Joining, Quarter of Joining, Half of Joining, Year of Joining, Month of Joining, Month Name of Joining, Short Month, Day of Joining, DOW of Joining, Short DOW, Age in Company (Years), Salary, Last % Hike, SSN, Phone No. , Place Name, County, City, State, Zip, Region, User Name, Password]
Index: []

[0 rows x 37 columns]
    Emp ID Name Prefix   First Name Middle Initial   Last Name Gender  \
0   677509        Drs.         Lois              H      Walker      F
7   380086        Mrs.        Carol              V      Murphy      F
9   162402        Hon.        Diana              T    Peterson      F
11  153989       Prof.         Jack              C   Alexander      M
12  386158        Mrs.      Melissa              Q        King      F
14  441771        Mrs.       Cheryl              O       Scott      F
17  214352         Ms.      Theresa              G         Lee      F
18  890290        Hon.        Julia              S       Scott      F
21  969580       Prof.      Matthew              L      Turner      M
22  426038        Hon.         Joan              C     Stewart      F
25  477253        Mrs.         Anne              L     Russell      F
26  263480        Hon.       Daniel              K      Cooper      M
27  683826         Mr.        Roger              L     Roberts      M
28  474599        Drs.        Maria              W      Walker      F
35  333476        Hon.         Mary              P      Wilson      F
44  407061         Ms.    Elizabeth              Q     Jackson      F
46  702813         Mr.       Ernest              D    Martinez      M
47  524896         Ms.         Judy              Y   Hernandez      F
48  363065        Drs.        Nancy              L       Jones      F
50  958326         Mr.        Larry              T      Miller      M
51  447813        Mrs.          Ann              Q     Coleman      F
52  525955        Drs.         Judy              C    Gonzales      F
53  818384         Mr.        Peter              X  Washington      M
54  971640       Prof.     Clarence              A        Ross      M
55  253573         Ms.       Sharon              E       Lopez      F
56  904898        Drs.          Ann              Q      Cooper      F
58  491943        Mrs.        Nancy              P      Howard      F
61  241882         Ms.        Debra              G        Wood      F
63  940922        Hon.      Melissa              X      Butler      F
65  917395        Hon.  Christopher              D      Nelson      M
68  293459         Mr.       Steven              J    Phillips      M
69  732017         Ms.      Cynthia              J     Ramirez      F
71  478003        Hon.      Cynthia              X       White      F
77  870820         Ms.       Martha              G  Washington      F
78  806955         Mr.      William              G   Hernandez      M
79  325319        Hon.      Carolyn              F       Price      F
82  761821         Mr.       Ernest              G  Washington      M
83  400173         Ms.      Dorothy              K     Edwards      F
85  476433         Ms.      Lillian              N    Mitchell      F
87  623929       Prof.        Jimmy              R      Howard      M
89  212893         Ms.        Janet              Y   Henderson      F
90  185032         Mr.       Eugene              D       Perez      M
91  867084         Ms.      Deborah              E       Smith      F
94  489424         Dr.      Phillip              F       White      M
97  461593         Ms.       Nicole              O        Ward      F

                              E Mail       Father's Name       Mother's Name  \
0            lois.walker@hotmail.com       Donald Walker        Helen Walker
7             carol.murphy@gmail.com       Eugene Murphy    Katherine Murphy
9       diana.peterson@hotmail.co.uk   Jonathan Peterson  Christina Peterson
11          jack.alexander@gmail.com    Samuel Alexander    Sharon Alexander
12          melissa.king@comcast.net         Philip King          Maria King
14            cheryl.scott@gmail.com       Richard Scott          Lois Scott
17             theresa.lee@gmail.com            John Lee         Rebecca Lee
18             julia.scott@apple.com      Lawrence Scott           Amy Scott
21          matthew.turner@gmail.com         Jose Turner        Kathy Turner
22            joan.stewart@yahoo.com     Charles Stewart       Julia Stewart
25              anne.russell@ibm.com       Jimmy Russell   Stephanie Russell
26           daniel.cooper@yahoo.com        Louis Cooper        Julie Cooper
27           roger.roberts@gmail.com     Antonio Roberts   Katherine Roberts
28        maria.walker@microsoft.com        Ralph Walker       Teresa Walker
35         mary.wilson@sbcglobal.net       Robert Wilson     Jennifer Wilson
44         elizabeth.jackson@aol.com       Scott Jackson   Catherine Jackson
46         ernest.martinez@gmail.com       Ryan Martinez    Beverly Martinez
47          judy.hernandez@gmail.com      Fred Hernandez    Pamela Hernandez
48             nancy.jones@gmail.com        Eugene Jones        Sandra Jones
50            larry.miller@shell.com      Russell Miller      Mildred Miller
51               ann.coleman@ibm.com      Harold Coleman        Tina Coleman
52           judy.gonzales@gmail.com      Kevin Gonzales     Sharon Gonzales
53           peter.washington@bp.com  Douglas Washington     Jean Washington
54           clarence.ross@apple.com         Arthur Ross         Louise Ross
55            sharon.lopez@gmail.com        Daniel Lopez         Susan Lopez
56         ann.cooper@exxonmobil.com       Harold Cooper      Mildred Cooper
58            nancy.howard@gmail.com      Gregory Howard      Mildred Howard
61            debra.wood@hotmail.com         Martin Wood        Theresa Wood
63        melissa.butler@hotmail.com       Robert Butler         Anne Butler
65        christopher.nelson@aol.com      Jeffrey Nelson      Cynthia Nelson
68       steven.phillips@hotmail.com      Jason Phillips     Gloria Phillips
69    cynthia.ramirez@btinternet.com      Walter Ramirez      Evelyn Ramirez
71           cynthia.white@gmail.com      Nicholas White     Katherine White
77         martha.washington@aol.com     Todd Washington  Carolyn Washington
78  william.hernandez@rediffmail.com     Peter Hernandez   Deborah Hernandez
79           carolyn.price@yahoo.com         Kevin Price      Patricia Price
82         ernest.washington@msn.com   Johnny Washington  Shirley Washington
83     dorothy.edwards@hotmail.co.uk      Dennis Edwards       Betty Edwards
85          lillian.mitchell@shaw.ca      Harry Mitchell      Marie Mitchell
87            jimmy.howard@yahoo.com     Nicholas Howard     Patricia Howard
89      janet.henderson@ntlworld.com     Jerry Henderson     Julie Henderson
90       eugene.perez@exxonmobil.com         Jimmy Perez          Lois Perez
91           deborah.smith@yahoo.com       Richard Smith         Diana Smith
94           phillip.white@gmail.com        Harold White       Frances White
97             nicole.ward@yahoo.com          Ralph Ward          Julia Ward

   Mother's Maiden Name  ...          SSN    Phone No.         Place Name  \
0                 Lewis  ...  467-99-4677  303-572-8492            Denver
7              Peterson  ...  423-67-7023  216-336-0009       Blanchester
9                  Ross  ...  512-33-6767  479-783-5656    Eureka Springs
11               Walker  ...  428-99-9413  702-603-3769         Las Vegas
12                White  ...  277-17-9106  216-605-3731     New Matamoras
14               Watson  ...  596-94-2279  215-288-9345          Quecreek
17               Turner  ...  055-02-9969  319-553-8919       Toeterville
18                 King  ...  251-99-1941  423-939-1010     Primm Springs
21                  Cox  ...  598-92-1988  236-972-7624       Heathsville
22              Collins  ...  429-99-6443  216-637-6800        Middleport
25           Richardson  ...  456-99-5619  605-635-1306         Stockholm
26               Murphy  ...  181-86-2024  701-510-8162           Manning
27               Brooks  ...  120-98-6493  206-497-3141      Mount Vernon
28               Brooks  ...  447-27-3175  423-668-5506      Lawrenceburg
35            Patterson  ...  198-84-0652  423-937-8660         Nashville
44              Jackson  ...  660-24-4434  603-568-6118         Rochester
46                 Hill  ...  672-48-7749  479-951-4138         Uniontown
47                Evans  ...  534-71-4481  316-736-6126            Topeka
48              Jenkins  ...  681-24-3165  212-825-1930     New York City
50                 Ward  ...  207-84-9482  217-574-9283  East Saint Louis
51               Walker  ...  027-92-0557  319-994-4179           Hancock
52                Perez  ...  029-92-2155  201-640-8645         Eatontown
53            Henderson  ...  039-74-8867  231-322-0316           Portage
54           Washington  ...  372-37-5315  423-772-0118            Oneida
55                Hayes  ...  064-02-2589  304-934-5548           Bartley
56             Williams  ...  219-89-6310  406-278-6460             Arlee
58               Flores  ...  035-74-2732  236-973-8086              Saxe
61                Perry  ...  342-11-6695  308-646-6219             Blair
63              Jackson  ...  301-15-9149  308-827-9016           Maxwell
65              Sanders  ...  120-98-6155  480-946-9780      Willow Beach
68                Lewis  ...  578-53-9940  225-968-5952       Baton Rouge
69                Smith  ...  355-08-4606  406-961-7340          Browning
71               Turner  ...  364-39-4983  314-593-3092       Kansas City
77                 Reed  ...  416-67-0297  405-945-0242            Nardin
78                Jones  ...  629-31-9010  239-276-0532       Mary Esther
79             Williams  ...  512-33-3410  217-409-4338           Wheaton
82               Harris  ...  178-86-1878  212-596-1659      Saranac Lake
83               Howard  ...  543-81-2192  215-902-6888      Philadelphia
85               Murphy  ...  505-59-3960  316-876-1484           Wichita
87                Hayes  ...  610-87-0251  212-855-9316          Oriskany
89               Cooper  ...  018-94-7340  239-769-6347             Miami
90                 Hall  ...  192-86-6418  262-472-7112            Racine
91              Bennett  ...  173-86-6203  907-279-8694           Atqasuk
94               Carter  ...  447-27-9469  503-668-6592          Mapleton
97                  Lee  ...  196-84-2551  231-761-7861           Detroit

              County              City State    Zip     Region     User Name  \
0             Denver            Denver    CO  80224       West      lhwalker
7            Clinton       Blanchester    OH  45107    Midwest      cvmurphy
9            Carroll    Eureka Springs    AR  72632      South    dtpeterson
11             Clark         Las Vegas    NV  89170       West   jcalexander
12        Washington     New Matamoras    OH  45767    Midwest        mqking
14          Somerset          Quecreek    PA  15555  Northeast       coscott
17          Mitchell       Toeterville    IA  50481    Midwest         tglee
18           Hickman     Primm Springs    TN  38476      South       jsscott
21    Northumberland       Heathsville    VA  22473      South      mlturner
22             Meigs        Middleport    OH  45760    Midwest     jcstewart
25             Grant         Stockholm    SD  57264    Midwest     alrussell
26              Dunn           Manning    ND  58642    Midwest      dkcooper
27            Skagit      Mount Vernon    WA  98273       West     rlroberts
28          Lawrence      Lawrenceburg    TN  38464      South      mwwalker
35          Davidson         Nashville    TN  37219      South      mpwilson
44         Strafford         Rochester    NH   3867  Northeast     eqjackson
46          Crawford         Uniontown    AR  72955      South    edmartinez
47           Shawnee            Topeka    KS  66606    Midwest   jyhernandez
48          New York     New York City    NY  10087  Northeast       nljones
50         St. Clair  East Saint Louis    IL  62201    Midwest      ltmiller
51     Pottawattamie           Hancock    IA  51536    Midwest     aqcoleman
52          Monmouth         Eatontown    NJ   7724  Northeast    jcgonzales
53         Kalamazoo           Portage    MI  49024    Midwest  pxwashington
54             Scott            Oneida    TN  37841      South        caross
55          McDowell           Bartley    WV  24813      South       selopez
56              Lake             Arlee    MT  59821       West      aqcooper
58         Charlotte              Saxe    VA  23967      South      nphoward
61        Washington             Blair    NE  68009    Midwest        dgwood
63           Lincoln           Maxwell    NE  69151    Midwest      mxbutler
65            Mohave      Willow Beach    AZ  86445       West      cdnelson
68  East Baton Rouge       Baton Rouge    LA  70833      South    sjphillips
69           Glacier          Browning    MT  59417       West     cjramirez
71           Jackson       Kansas City    MO  64133    Midwest       cxwhite
77               Kay            Nardin    OK  74646      South  mgwashington
78          Okaloosa       Mary Esther    FL  32569      South   wghernandez
79            DuPage           Wheaton    IL  60189    Midwest       cfprice
82          Franklin      Saranac Lake    NY  12983  Northeast  egwashington
83      Philadelphia      Philadelphia    PA  19132  Northeast     dkedwards
85          Sedgwick           Wichita    KS  67214    Midwest    lnmitchell
87            Oneida          Oriskany    NY  13424  Northeast      jrhoward
89        Miami-Dade             Miami    FL  33166      South   jyhenderson
90            Racine            Racine    WI  53490    Midwest       edperez
91       North Slope           Atqasuk    AK  99791       West       desmith
94              Lane          Mapleton    OR  97453       West       pfwhite
97             Wayne           Detroit    MI  48278    Midwest        noward

           Password
0     DCa}.T}X:v?NP
7      Uc+VG%vuZU<k
9    3o8>v&tYxjyEAo
11   9L*-O1U.9mSUSh
12   FE5i<e-Y}[4f78
14      Vbb+~2N|_yR
17   JS#hN&Xij\%QEr
18       r.:Q7c^Tpb
21  I>tL>d[|lZdi_|^
22   q@mq.U~D#1MPgZ
25     c8Nk&Y^~Vz!2
26   d8p{Pwx2fsW0-Z
27  41:C_0ik|Jb0iTO
28        cw?%U}s{?
35        Pwl&W:|<_
44  EAHcnWsf6xMRwr]
46  qe?JNGBY{[\7;dD
47  kiB:v!j&?D!&NYY
48    J}HJq/zVF-Aq2
50     2WgF#:ew**x#
51        g2]GlvlL5
52   yDl}pfaWs{Hro6
53  97%d^2rk41!E>*Q
54     h&jmac@+QD?B
55        GsP~S?FYY
56       i_^#>]tFpt
58        OC\&tG&?c
61  iO8B@*yA*mG6b9o
63       hY3BqUR>6F
65   QKae{1EP1A[SeX
68      ht}X55$P&g1
69   qP-#AhuNuz*Wb]
71   mofyGR>.?Dwb4!
77      ju$7I]eH8{-
78     BRB3DFywgZZ4
79        K*$u@MAoH
82         B\Wb^6W-
83    VWEIm3YKm65|D
85         Ty/b@+;f
87   0v+|SfA0Xv+Pf%
89       g-oCs-L/za
90       g]SJn<W_/#
91         C[WxHsB9
94   8<Mc.5]eu.*C8.
97   AUe6s0@:@]A3Ze

[45 rows x 37 columns]

### 12. How many people are from the southern region joined on Monday?

In [52]:
# YOUR CODE HERE
subset2 = dataset1[(dataset1['Region']=='South') & (dataset1['DOW of Joining'] == 'Monday')]
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', None)
print(subset2)
print(subset2.head(3).style)

    Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
9   162402        Hon.      Diana              T  Peterson      F
15  528509        Hon.      Paula              G      Diaz      F
20  979607         Ms.      Carol              J   Edwards      F
30  329752        Hon.    Lillian              X     Brown      F
57  515103         Ms.       Anne              A     Perez      F
59  750173         Mr.    Antonio              R   Roberts      M
74  528673        Hon.       Paul              V    Watson      M
76  262382         Ms.     Cheryl              O    Miller      F
81  225925         Mr.       Paul              D    Cooper      M

                          E Mail      Father's Name       Mother's Name  \
9   diana.peterson@hotmail.co.uk  Jonathan Peterson  Christina Peterson
15          paula.diaz@gmail.com          Alan Diaz        Kathryn Diaz
20         carol.edwards@msn.com      Shawn Edwards       Susan Edwards
30         lillian.brown@aol.com         Gary Brown      Virginia Brown
57      anne.perez@sbcglobal.net      Douglas Perez         Doris Perez
59   antonio.roberts@hotmail.com    Timothy Roberts       Diana Roberts
74       paul.watson@hotmail.com        Carl Watson         Anna Watson
76    cheryl.miller@ntlworld.com      Gerald Miller    Christine Miller
81         paul.cooper@gmail.com    Nicholas Cooper        Helen Cooper

   Mother's Maiden Name Date of Birth Time of Birth  Age in Yrs.  \
9                  Ross    11/13/1987   03:59:26 AM        29.73
15               Powell     8/22/1966   08:11:15 PM        50.97
20                 Gray    12/14/1994   09:28:36 AM        22.64
30                 Wood     5/12/1981   12:00:55 AM        36.24
57               Bailey      5/5/1958   01:44:42 AM        59.27
59            Rodriguez     8/27/1995   02:47:04 PM        21.93
74              Bennett      3/9/1959   05:19:17 AM        58.43
76             Mitchell     4/20/1985   05:42:38 PM        32.29
81                 Hill     8/12/1991   11:14:26 PM        25.98

    Weight in Kgs. Date of Joining Quarter of Joining Half of Joining  \
9               60       2/17/2014                 Q1              H1
15              42       8/22/1994                 Q3              H2
20              56       4/25/2016                 Q2              H1
30              49       4/13/2015                 Q2              H1
57              48       7/28/2003                 Q3              H2
59              82        5/1/2017                 Q2              H1
74              60       6/26/1995                 Q2              H1
76              48       7/30/2007                 Q3              H2
81              68        9/8/2014                 Q3              H2

    Year of Joining  Month of Joining Month Name of Joining Short Month  \
9              2014                 2              February         Feb
15             1994                 8                August         Aug
20             2016                 4                 April         Apr
30             2015                 4                 April         Apr
57             2003                 7                  July         Jul
59             2017                 5                   May         May
74             1995                 6                  June         Jun
76             2007                 7                  July         Jul
81             2014                 9             September         Sep

    Day of Joining DOW of Joining Short DOW  Age in Company (Years)  Salary  \
9               17         Monday       Mon                    3.44   43010
15              22         Monday       Mon                   22.95  152654
20              25         Monday       Mon                    1.26   93967
30              13         Monday       Mon                    2.29   67251
57              28         Monday       Mon                   14.01  114426
59               1         Monday       Mon                    0.24  181646
74              26         Monday       Mon                   22.10  145235
76              30         Monday       Mon                   10.00   64143
81               8         Monday       Mon                    2.89   73526

   Last % Hike          SSN    Phone No.       Place Name     County  \
9           4%  512-33-6767  479-783-5656  Eureka Springs    Carroll
15          8%  234-57-7671  252-531-7641      Beulaville     Duplin
20         30%  316-35-9870  225-283-4295      Shreveport      Caddo
30         22%  249-99-8821  239-812-9041         Panacea    Wakulla
57          9%  594-99-9091  423-837-3338      Cookeville     Putnam
59         30%  281-15-7944  205-267-7304        Mc Calla  Jefferson
74         15%  286-15-9671  270-556-7711      Blue River      Floyd
76          3%  287-15-4772  270-880-3858            Bays  Breathitt
81         27%  613-87-0084  210-984-4722         Glidden   Colorado

              City State    Zip Region   User Name        Password
9   Eureka Springs    AR  72632  South  dtpeterson  3o8>v&tYxjyEAo
15      Beulaville    NC  28518  South      pgdiaz        3Kg55luU
20      Shreveport    LA  71162  South   cjedwards       wi>v-a9gt
30         Panacea    FL  32346  South     lxbrown        CG-M5~z:
57      Cookeville    TN  38505  South     aaperez        y;n9A#}b
59        Mc Calla    AL  35111  South   arroberts     h>.g!B:VcNN
74      Blue River    KY  41607  South    pvwatson    7q{iHhbgWZ7%
76            Bays    KY  41310  South    comiller     Nr-t/.^cWBO
81         Glidden    TX  78943  South    pdcooper      hW%ZbJ\fZ-
<pandas.io.formats.style.Styler object at 0x7f82699a02c0>

### 13. Display the information of the employees who have more than 13 years experience in the company

In [55]:
# YOUR CODE HERE
empexpgreaterthan13 = dataset1[dataset1['Age in Company (Years)'] > 13]
empexpgreaterthan13

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,Time of Birth,Age in Yrs.,Weight in Kgs.,Date of Joining,Quarter of Joining,Half of Joining,Year of Joining,Month of Joining,Month Name of Joining,Short Month,Day of Joining,DOW of Joining,Short DOW,Age in Company (Years),Salary,Last % Hike,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,3/29/1981,02:31:49 AM,36.36,60,11/24/2003,Q4,H2,2003,11,November,Nov,24,Monday,Mon,13.68,168251,21%,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,12/4/1977,02:18:45 AM,39.67,51,4/16/1999,Q2,H1,1999,4,April,Apr,16,Friday,Fri,18.30,180294,1%,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
7,380086,Mrs.,Carol,V,Murphy,F,carol.murphy@gmail.com,Eugene Murphy,Katherine Murphy,Peterson,6/30/1958,10:39:33 AM,59.12,40,1/28/1983,Q1,H1,1983,1,January,Jan,28,Friday,Fri,34.52,60918,20%,423-67-7023,216-336-0009,Blanchester,Clinton,Blanchester,OH,45107,Midwest,cvmurphy,Uc+VG%vuZU<k
8,477616,Hon.,Frances,B,Young,F,frances.young@gmail.com,Fred Young,Lillian Young,Diaz,6/9/1959,04:38:47 PM,58.18,42,4/27/1994,Q2,H1,1994,4,April,Apr,27,Wednesday,Wed,23.27,121587,28%,028-92-8912,210-819-9765,Delmita,Starr,Delmita,TX,78536,South,fbyoung,K}^USc0l7[A
14,441771,Mrs.,Cheryl,O,Scott,F,cheryl.scott@gmail.com,Richard Scott,Lois Scott,Watson,2/23/1958,06:59:29 PM,59.47,47,11/26/1990,Q4,H2,1990,11,November,Nov,26,Monday,Mon,26.69,92220,12%,596-94-2279,215-288-9345,Quecreek,Somerset,Quecreek,PA,15555,Northeast,coscott,Vbb+~2N|_yR
15,528509,Hon.,Paula,G,Diaz,F,paula.diaz@gmail.com,Alan Diaz,Kathryn Diaz,Powell,8/22/1966,08:11:15 PM,50.97,42,8/22/1994,Q3,H2,1994,8,August,Aug,22,Monday,Mon,22.95,152654,8%,234-57-7671,252-531-7641,Beulaville,Duplin,Beulaville,NC,28518,South,pgdiaz,3Kg55luU
16,912990,Mr.,Joshua,T,Stewart,M,joshua.stewart@yahoo.ca,Todd Stewart,Martha Stewart,Jones,5/18/1970,03:47:46 AM,47.23,68,9/2/2002,Q3,H2,2002,9,September,Sep,2,Monday,Mon,14.91,184896,1%,755-07-3676,217-279-9342,New Douglas,Madison,New Douglas,IL,62074,Midwest,jtstewart,K?vi9BBznj
19,622406,Mr.,Thomas,Q,Lewis,M,thomas.lewis@gmail.com,Ryan Lewis,Lois Lewis,Price,10/4/1967,08:28:14 PM,49.85,73,6/7/1998,Q2,H1,1998,6,June,Jun,7,Sunday,Sun,19.15,73862,3%,467-99-2604,314-679-3697,Dutchtown,Cape Girardeau,Dutchtown,MO,63745,Midwest,tqlewis,y;OJd_Oa#4g|!G
24,560455,Ms.,Carolyn,V,Hayes,F,carolyn.hayes@hotmail.co.uk,Jimmy Hayes,Sara Hayes,Foster,3/10/1958,12:52:37 PM,59.42,53,7/3/2001,Q3,H2,2001,7,July,Jul,3,Tuesday,Tue,16.08,42005,14%,730-28-1350,239-882-8784,Saint Cloud,Osceola,Saint Cloud,FL,34771,South,cvhayes,NY!Y2sw.[_v-Q9{
28,474599,Drs.,Maria,W,Walker,F,maria.walker@microsoft.com,Ralph Walker,Teresa Walker,Brooks,3/19/1975,11:07:50 PM,42.39,41,10/1/1998,Q4,H2,1998,10,October,Oct,1,Thursday,Thu,18.84,48944,21%,447-27-3175,423-668-5506,Lawrenceburg,Lawrence,Lawrenceburg,TN,38464,South,mwwalker,cw?%U}s{?
29,335732,Ms.,Brenda,M,Butler,F,brenda.butler@gmail.com,Phillip Butler,Joyce Butler,Thomas,12/6/1963,03:15:30 AM,53.68,41,8/20/1987,Q3,H2,1987,8,August,Aug,20,Thursday,Thu,29.96,60508,29%,282-15-6434,480-814-8284,Mesa,Maricopa,Mesa,AZ,85208,West,bmbutler,u+CtpZ~gyR*>
31,893212,Ms.,Amy,B,Howard,F,amy.howard@aol.com,James Howard,Virginia Howard,Collins,6/16/1981,04:20:22 AM,36.14,52,6/1/2003,Q2,H1,2003,6,June,Jun,1,Sunday,Sun,14.17,112715,30%,686-24-2843,803-613-3168,Kline,Kline,Kline,SC,29814,South,abhoward,tNo::TEG
35,333476,Hon.,Mary,P,Wilson,F,mary.wilson@sbcglobal.net,Robert Wilson,Jennifer Wilson,Patterson,12/1/1967,01:45:41 AM,49.69,54,12/22/1991,Q4,H2,1991,12,December,Dec,22,Sunday,Sun,25.62,109394,16%,198-84-0652,423-937-8660,Nashville,Davidson,Nashville,TN,37219,South,mpwilson,Pwl&W:|<_
36,218791,Mr.,Aaron,N,Price,M,aaron.price@bp.com,Michael Price,Diana Price,Torres,2/10/1969,03:42:13 AM,48.49,56,7/3/1997,Q3,H2,1997,7,July,Jul,3,Thursday,Thu,20.08,54402,0%,491-29-5152,219-287-8926,Eckerty,Crawford,Eckerty,IN,47116,Midwest,anprice,uKxgV4uO&k@
40,923947,Ms.,Mary,G,Bryant,F,mary.bryant@verizon.net,Joshua Bryant,Norma Bryant,Harris,6/21/1962,12:02:11 AM,55.14,45,5/20/2004,Q2,H1,2004,5,May,May,20,Thursday,Thu,13.20,155442,4%,491-29-7461,319-827-3516,Conroy,Iowa,Conroy,IA,52220,Midwest,mgbryant,A[iR?Z1{
52,525955,Drs.,Judy,C,Gonzales,F,judy.gonzales@gmail.com,Kevin Gonzales,Sharon Gonzales,Perez,6/17/1959,07:11:37 PM,58.15,51,1/3/1992,Q1,H1,1992,1,January,Jan,3,Friday,Fri,25.58,149575,9%,029-92-2155,201-640-8645,Eatontown,Monmouth,Eatontown,NJ,7724,Northeast,jcgonzales,yDl}pfaWs{Hro6
57,515103,Ms.,Anne,A,Perez,F,anne.perez@sbcglobal.net,Douglas Perez,Doris Perez,Bailey,5/5/1958,01:44:42 AM,59.27,48,7/28/2003,Q3,H2,2003,7,July,Jul,28,Monday,Mon,14.01,114426,9%,594-99-9091,423-837-3338,Cookeville,Putnam,Cookeville,TN,38505,South,aaperez,y;n9A#}b
58,491943,Mrs.,Nancy,P,Howard,F,nancy.howard@gmail.com,Gregory Howard,Mildred Howard,Flores,5/5/1961,09:17:37 PM,56.27,45,2/6/1999,Q1,H1,1999,2,February,Feb,6,Saturday,Sat,18.48,101553,25%,035-74-2732,236-973-8086,Saxe,Charlotte,Saxe,VA,23967,South,nphoward,OC\&tG&?c
61,241882,Ms.,Debra,G,Wood,F,debra.wood@hotmail.com,Martin Wood,Theresa Wood,Perry,10/30/1969,06:58:21 AM,47.78,54,1/10/1991,Q1,H1,1991,1,January,Jan,10,Thursday,Thu,26.56,84318,19%,342-11-6695,308-646-6219,Blair,Washington,Blair,NE,68009,Midwest,dgwood,iO8B@*yA*mG6b9o
65,917395,Hon.,Christopher,D,Nelson,M,christopher.nelson@aol.com,Jeffrey Nelson,Cynthia Nelson,Sanders,3/29/1960,05:56:17 PM,57.37,62,11/8/1997,Q4,H2,1997,11,November,Nov,8,Saturday,Sat,19.73,190765,0%,120-98-6155,480-946-9780,Willow Beach,Mohave,Willow Beach,AZ,86445,West,cdnelson,QKae{1EP1A[SeX
70,915638,Dr.,Jason,W,Anderson,M,jason.anderson@gmail.com,Brandon Anderson,Julia Anderson,Baker,1/3/1974,06:47:06 PM,43.59,57,9/21/1999,Q3,H2,1999,9,September,Sep,21,Tuesday,Tue,17.86,76636,19%,048-15-7937,217-856-6752,Hudson,McLean,Hudson,IL,61748,Midwest,jwanderson,a3Hlk+.V/TjD
71,478003,Hon.,Cynthia,X,White,F,cynthia.white@gmail.com,Nicholas White,Katherine White,Turner,6/15/1963,12:19:06 PM,54.16,60,3/4/2004,Q1,H1,2004,3,March,Mar,4,Thursday,Thu,13.41,186200,30%,364-39-4983,314-593-3092,Kansas City,Jackson,Kansas City,MO,64133,Midwest,cxwhite,mofyGR>.?Dwb4!
74,528673,Hon.,Paul,V,Watson,M,paul.watson@hotmail.com,Carl Watson,Anna Watson,Bennett,3/9/1959,05:19:17 AM,58.43,60,6/26/1995,Q2,H1,1995,6,June,Jun,26,Monday,Mon,22.10,145235,15%,286-15-9671,270-556-7711,Blue River,Floyd,Blue River,KY,41607,South,pvwatson,7q{iHhbgWZ7%
78,806955,Mr.,William,G,Hernandez,M,william.hernandez@rediffmail.com,Peter Hernandez,Deborah Hernandez,Jones,7/22/1967,08:22:32 AM,50.05,50,3/21/2000,Q1,H1,2000,3,March,Mar,21,Tuesday,Tue,17.36,73734,22%,629-31-9010,239-276-0532,Mary Esther,Okaloosa,Mary Esther,FL,32569,South,wghernandez,BRB3DFywgZZ4
85,476433,Ms.,Lillian,N,Mitchell,F,lillian.mitchell@shaw.ca,Harry Mitchell,Marie Mitchell,Murphy,10/23/1974,06:40:13 PM,42.79,55,12/7/1999,Q4,H2,1999,12,December,Dec,7,Tuesday,Tue,17.65,149878,3%,505-59-3960,316-876-1484,Wichita,Sedgwick,Wichita,KS,67214,Midwest,lnmitchell,Ty/b@+;f
91,867084,Ms.,Deborah,E,Smith,F,deborah.smith@yahoo.com,Richard Smith,Diana Smith,Bennett,10/31/1977,08:14:09 PM,39.77,54,3/4/2002,Q1,H1,2002,3,March,Mar,4,Monday,Mon,15.41,52767,28%,173-86-6203,907-279-8694,Atqasuk,North Slope,Atqasuk,AK,99791,West,desmith,C[WxHsB9
93,158666,Ms.,Rebecca,A,Stewart,F,rebecca.stewart@gmail.com,Roger Stewart,Carol Stewart,Cox,8/11/1961,11:08:01 PM,56.00,55,4/10/1983,Q2,H1,1983,4,April,Apr,10,Sunday,Sun,34.32,160043,9%,202-84-8294,209-233-7631,Independence,Inyo,Independence,CA,93526,West,rastewart,7ONuh3Zi^z#32r
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,12/12/1964,07:12:20 AM,52.66,60,1/23/1989,Q1,H1,1989,1,January,Jan,23,Monday,Mon,28.53,95673,12%,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze

### 14. There is a lot of redundant data. For example, the information in the below columns is also available in the *Date of Joining* column.

  1.   month of Joining
  2.   year of Joining
  3.   Day of Joining

There could be other such columns containing redundant data. Please identify such columns and take appropriate action.


You can refer to the below link :

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [61]:
# YOUR CODE HERE
dataset1.T.duplicated()
#dataset1.corr()
dataset.nunique()
dataset2 = dataset1.drop(['Month of Joining', 'Year of Joining', 'Day of Joining', 'Month Name of Joining'], axis=1)
dataset2

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,Time of Birth,Age in Yrs.,Weight in Kgs.,Date of Joining,Quarter of Joining,Half of Joining,Short Month,DOW of Joining,Short DOW,Age in Company (Years),Salary,Last % Hike,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,3/29/1981,02:31:49 AM,36.36,60,11/24/2003,Q4,H2,Nov,Monday,Mon,13.68,168251,21%,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,7/31/1970,12:13:27 PM,47.02,60,7/27/2008,Q3,H2,Jul,Sunday,Sun,9.01,51063,27%,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,6/16/1963,10:45:36 AM,54.15,68,8/3/2016,Q3,H2,Aug,Wednesday,Wed,0.98,50155,16%,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,12/4/1977,02:18:45 AM,39.67,51,4/16/1999,Q2,H1,Apr,Friday,Fri,18.30,180294,1%,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,4/17/1977,05:41:11 PM,40.31,58,7/25/2013,Q3,H2,Jul,Thursday,Thu,4.01,117642,13%,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,10/8/1994,05:23:39 AM,22.82,89,7/9/2016,Q3,H2,Jul,Saturday,Sat,1.05,129774,15%,171-86-3825,228-245-5000,Biloxi,Harrison,Biloxi,MS,39532,South,jkhill,a_!SKb6h3?w*Mad
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,12/24/1984,09:00:17 PM,32.61,77,8/23/2011,Q3,H2,Aug,Tuesday,Tue,5.93,156194,0%,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,12/12/1964,07:12:20 AM,52.66,60,1/23/1989,Q1,H1,Jan,Monday,Mon,28.53,95673,12%,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,12/30/1987,05:56:10 AM,29.60,57,8/3/2010,Q3,H2,Aug,Tuesday,Tue,6.99,51015,11%,249-99-8801,907-356-1555,Mc Grath,Yukon-Koyukuk (CA),Mc Grath,AK,99627,West,trmurphy,V]PGw>4h9
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,3/22/1979,10:26:52 PM,38.38,55,4/25/2015,Q2,H1,Apr,Saturday,Sat,2.26,93650,7%,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

### 15. Remove "%" sign from the "Last % Hike" column values of the dataset

you can refer the below link :

https://stackoverflow.com/questions/52850192/python-extract-last-letter-of-a-string-from-a-pandas-column

In [ ]:
# YOUR CODE HERE
dataset1['Last % Hike'] = dataset1['Last % Hike'].str.replace('%','').astype(float)

### 16. How many Female employees got hike more than 20% ?

In [67]:
# YOUR CODE HERE
#dataset1['Last % Hike'] = dataset1['Last % Hike'].str.replace('%','').astype(float)

fem_hike_20= dataset1[(dataset1['Gender']=='F') & (dataset1['Last % Hike'] > 21)]
fem_hike_20

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,Date of Birth,Time of Birth,Age in Yrs.,Weight in Kgs.,Date of Joining,Quarter of Joining,Half of Joining,Year of Joining,Month of Joining,Month Name of Joining,Short Month,Day of Joining,DOW of Joining,Short DOW,Age in Company (Years),Salary,Last % Hike,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,7/31/1970,12:13:27 PM,47.02,60,7/27/2008,Q3,H2,2008,7,July,Jul,27,Sunday,Sun,9.01,51063,27.0,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
8,477616,Hon.,Frances,B,Young,F,frances.young@gmail.com,Fred Young,Lillian Young,Diaz,6/9/1959,04:38:47 PM,58.18,42,4/27/1994,Q2,H1,1994,4,April,Apr,27,Wednesday,Wed,23.27,121587,28.0,028-92-8912,210-819-9765,Delmita,Starr,Delmita,TX,78536,South,fbyoung,K}^USc0l7[A
20,979607,Ms.,Carol,J,Edwards,F,carol.edwards@msn.com,Shawn Edwards,Susan Edwards,Gray,12/14/1994,09:28:36 AM,22.64,56,4/25/2016,Q2,H1,2016,4,April,Apr,25,Monday,Mon,1.26,93967,30.0,316-35-9870,225-283-4295,Shreveport,Caddo,Shreveport,LA,71162,South,cjedwards,wi>v-a9gt
25,477253,Mrs.,Anne,L,Russell,F,anne.russell@ibm.com,Jimmy Russell,Stephanie Russell,Richardson,7/29/1989,02:57:12 AM,28.02,60,11/24/2013,Q4,H2,2013,11,November,Nov,24,Sunday,Sun,3.68,103160,29.0,456-99-5619,605-635-1306,Stockholm,Grant,Stockholm,SD,57264,Midwest,alrussell,c8Nk&Y^~Vz!2
29,335732,Ms.,Brenda,M,Butler,F,brenda.butler@gmail.com,Phillip Butler,Joyce Butler,Thomas,12/6/1963,03:15:30 AM,53.68,41,8/20/1987,Q3,H2,1987,8,August,Aug,20,Thursday,Thu,29.96,60508,29.0,282-15-6434,480-814-8284,Mesa,Maricopa,Mesa,AZ,85208,West,bmbutler,u+CtpZ~gyR*>
30,329752,Hon.,Lillian,X,Brown,F,lillian.brown@aol.com,Gary Brown,Virginia Brown,Wood,5/12/1981,12:00:55 AM,36.24,49,4/13/2015,Q2,H1,2015,4,April,Apr,13,Monday,Mon,2.29,67251,22.0,249-99-8821,239-812-9041,Panacea,Wakulla,Panacea,FL,32346,South,lxbrown,CG-M5~z:
31,893212,Ms.,Amy,B,Howard,F,amy.howard@aol.com,James Howard,Virginia Howard,Collins,6/16/1981,04:20:22 AM,36.14,52,6/1/2003,Q2,H1,2003,6,June,Jun,1,Sunday,Sun,14.17,112715,30.0,686-24-2843,803-613-3168,Kline,Kline,Kline,SC,29814,South,abhoward,tNo::TEG
41,227922,Hon.,Amanda,M,Hughes,F,amanda.hughes@rediffmail.com,Roy Hughes,Cynthia Hughes,Bryant,7/29/1982,02:43:26 AM,35.02,40,4/19/2007,Q2,H1,2007,4,April,Apr,19,Thursday,Thu,10.28,114257,22.0,311-35-2540,225-544-9700,Lake Charles,Calcasieu,Lake Charles,LA,70605,South,amhughes,B2N>J{_k7]F
44,407061,Ms.,Elizabeth,Q,Jackson,F,elizabeth.jackson@aol.com,Scott Jackson,Catherine Jackson,Jackson,8/15/1964,05:45:35 AM,52.99,56,1/19/2005,Q1,H1,2005,1,January,Jan,19,Wednesday,Wed,12.53,85420,24.0,660-24-4434,603-568-6118,Rochester,Strafford,Rochester,NH,3867,Northeast,eqjackson,EAHcnWsf6xMRwr]
47,524896,Ms.,Judy,Y,Hernandez,F,judy.hernandez@gmail.com,Fred Hernandez,Pamela Hernandez,Evans,3/25/1961,05:49:46 AM,56.38,40,12/27/2011,Q4,H2,2011,12,December,Dec,27,Tuesday,Tue,5.59,133332,30.0,534-71-4481,316-736-6126,Topeka,Shawnee,Topeka,KS,66606,Midwest,jyhernandez,kiB:v!j&?D!&NYY
56,904898,Drs.,Ann,Q,Cooper,F,ann.cooper@exxonmobil.com,Harold Cooper,Mildred Cooper,Williams,12/25/1992,03:01:52 AM,24.61,44,2/15/2017,Q1,H1,2017,2,February,Feb,15,Wednesday,Wed,0.45,182521,30.0,219-89-6310,406-278-6460,Arlee,Lake,Arlee,MT,59821,West,aqcooper,i_^#>]tFpt
58,491943,Mrs.,Nancy,P,Howard,F,nancy.howard@gmail.com,Gregory Howard,Mildred Howard,Flores,5/5/1961,09:17:37 PM,56.27,45,2/6/1999,Q1,H1,1999,2,February,Feb,6,Saturday,Sat,18.48,101553,25.0,035-74-2732,236-973-8086,Saxe,Charlotte,Saxe,VA,23967,South,nphoward,OC\&tG&?c
60,687017,Ms.,Frances,P,Watson,F,frances.watson@outlook.com,Adam Watson,Diana Watson,Jones,1/30/1961,11:52:21 PM,56.53,42,8/20/2010,Q3,H2,2010,8,August,Aug,20,Friday,Fri,6.94,46945,22.0,305-37-1946,406-530-8069,Trego,Lincoln,Trego,MT,59934,West,fpwatson,rjV1$at!wq53a$
63,940922,Hon.,Melissa,X,Butler,F,melissa.butler@hotmail.com,Robert Butler,Anne Butler,Jackson,11/14/1994,08:44:14 AM,22.72,55,2/5/2017,Q1,H1,2017,2,February,Feb,5,Sunday,Sun,0.47,167631,30.0,301-15-9149,308-827-9016,Maxwell,Lincoln,Maxwell,NE,69151,Midwest,mxbutler,hY3BqUR>6F
66,183071,Drs.,Andrea,P,Garcia,F,andrea.garcia@aol.com,Mark Garcia,Nicole Garcia,Howard,7/6/1985,12:49:53 AM,32.08,52,4/18/2010,Q2,H1,2010,4,April,Apr,18,Sunday,Sun,7.28,54179,25.0,213-91-6792,219-624-3708,Granger,St. Joseph,Granger,IN,46530,Midwest,apgarcia,eI!^kXR]Q^V+
71,478003,Hon.,Cynthia,X,White,F,cynthia.white@gmail.com,Nicholas White,Katherine White,Turner,6/15/1963,12:19:06 PM,54.16,60,3/4/2004,Q1,H1,2004,3,March,Mar,4,Thursday,Thu,13.41,186200,30.0,364-39-4983,314-593-3092,Kansas City,Jackson,Kansas City,MO,64133,Midwest,cxwhite,mofyGR>.?Dwb4!
77,870820,Ms.,Martha,G,Washington,F,martha.washington@aol.com,Todd Washington,Carolyn Washington,Reed,3/28/1991,05:37:33 AM,26.35,54,3/3/2017,Q1,H1,2017,3,March,Mar,3,Friday,Fri,0.40,116629,25.0,416-67-0297,405-945-0242,Nardin,Kay,Nardin,OK,74646,South,mgwashington,ju$7I]eH8{-
88,844177,Ms.,Margaret,T,Allen,F,margaret.allen@gmail.com,Michael Allen,Karen Allen,Morris,9/8/1981,10:10:26 PM,35.91,43,5/17/2013,Q2,H1,2013,5,May,May,17,Friday,Fri,4.20,180107,22.0,137-25-8468,216-697-6987,Richmond Dale,Ross,Richmond Dale,OH,45673,Midwest,mtallen,oC1OHlW%Sk@%6
91,867084,Ms.,Deborah,E,Smith,F,deborah.smith@yahoo.com,Richard Smith,Diana Smith,Bennett,10/31/1977,08:14:09 PM,39.77,54,3/4/2002,Q1,H1,2002,3,March,Mar,4,Monday,Mon,15.41,52767,28.0,173-86-6203,907-279-8694,Atqasuk,North Slope,Atqasuk,AK,99791,West,desmith,C[WxHsB9
92,969964,Hon.,Janice,S,Parker,F,janice.parker@yahoo.com,Paul Parker,Alice Parker,Perez,1/12/1980,08:38:06 AM,37.57,56,8/23/2016,Q3,H2,2016,8,August,Aug,23,Tuesday,Tue,0.93,147641,25.0,733-26-1976,314-842-5984,Whiteman Air Force Base,Johnson,Whiteman Air Force Base,MO,65305,Midwest,jsparker,8wUbWmuib

### Summary

To know more about Pandas, you can refer below link :

https://www.machinelearningplus.com/python/101-pandas-exercises-python/

### Please answer the questions below to complete the experiment:

In [68]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

In [75]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "I liked the exercise" #@param {type:"string"}

In [69]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]

In [70]:
#@title  Experiment walkthrough video? { run: "auto", vertical-output: true, display-mode: "form" }
Walkthrough = "Didn't use" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [71]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [72]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Not Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [76]:
#@title Run this cell to submit your notebook for Ungrading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 1007
Date of submission:  23 Nov 2025
Time of submission:  00:07:54
View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions